Update to 2.4.8 final.
PR1781: NSS PKCS11 provider fails to handle multipart AES encryption
RH905128: [CRASH] OpenJDK-1.7.0 while using NSS security provider and kerberos
S8029755, CVE-2014-4209: Enhance subject class
S8030763: Validate global memory allocation
S8031340, CVE-2014-4264: Better TLS/EC management
S8031346, CVE-2014-4244: Enhance RSA key handling
S8031540: Introduce document horizon
S8032536: JVM resolves wrong method in some unusual cases
S8033055: Issues in 2d
S8033301, CVE-2014-4266: Build more informative InfoBuilder
S8034267: Probabilistic native crash
S8034272: Do not cram data into CRAM arrays
S8034985, CVE-2014-2483: Better form for Lambda Forms
S8035004, CVE-2014-4252: Provider provides less service
S8035009, CVE-2014-4218: Make Proxy representations consistent
S8035119, CVE-2014-4219: Fix exceptions to bytecode verification
S8035699, CVE-2014-4268: File choosers should be choosier
S8035788. CVE-2014-4221: Provide more consistency for lookups
S8035793, CVE-2014-4223: Maximum arity maxed out
S8036571: (process) Process process arguments carefully
S8036800: Attribute OOM to correct part of code
S8037046: Validate libraries to be loaded
S8037076, CVE-2014-2490: Check constant pool constants
S8037157: Verify <init> call
S8037162, CVE-2014-4263: More robust DH exchanges
S8037167, CVE-2014-4216: Better method signature resolution
S8039520, CVE-2014-4262: More atomicity of atomic updates
S8001108: an attempt to use "<init>" as a method name should elicit NoSuchMethodException
S8001109: arity mismatch on a call to spreader method handle should elicit IllegalArgumentException
S8013611: Modal dialog fails to obtain keyboard focus
S8013809: deadlock in SSLSocketImpl between between write and close
S8013836: getFirstDayOfWeek reports wrong day for pt-BR locale
S8019990: IM candidate window appears on the South-East corner of the display.
S8023990: Regression: postscript size increase from 6u18
S8024283: 10 nashorn tests fail with similar stack trace InternalError with cause being NoClassDefFoundError
S8024616: JSR292: lazily initialize core NamedFunctions used for bootstrapping
S8027212: java/nio/channels/Selector/SelectAfterRead.java fails intermittently
S8028285: RMI Thread can no longer call out to AWT
S8029177: [Parfait] warnings from b117 for jdk.src.share.native.com.sun.java.util.jar: JNI exception pending
S8031075: [Regression] focus disappears with shift+tab on dialog having one focus component
S8032585: JSR292: IllegalAccessError when attempting to invoke protected method from different package
S8033278: Missed access checks for Lookup.unreflect* after 8032585
S8035613: With active Securitymanager JAXBContext.newInstance fails
S8036786: Update jdk7 testlibrary to match jdk8
S8037012: (tz) Support tzdata2014a
S8038306: (tz) Support tzdata2014b
S8038392: Generating prelink cache breaks JAVA 'jinfo' utility normal behavior
S8042264: 7u65 l10n resource file translation update 1
S8042582: Test java/awt/KeyboardFocusmanager/ChangeKFMTest/ChangeKFMTest.html fails on Windows x64
S8042590: Running form URL throws NPE
S8042789: org.omg.CORBA.ORBSingletonClass loading no longer uses context class loader
S8043012: (tz) Support tzdata2014c

2014-07-22  Andrew John Hughes  <gnu_andrew@member.fsf.org>

	* Makefile.am:
	(CORBA_CHANGESET): Update to icedtea-2.4.8 tag.
	(JAXP_CHANGESET): Likewise.
	(JAXWS_CHANGESET): Likewise.
	(JDK_CHANGESET): Likewise.
	(LANGTOOLS_CHANGESET): Likewise.
	(OPENJDK_CHANGESET): Likewise.
	(CORBA_SHA256SUM): Likewise.
	(JAXP_SHA256SUM): Likewise.
	(JAXWS_SHA256SUM): Likewise.
	(JDK_SHA256SUM): Likewise.
	(LANGTOOLS_SHA256SUM): Likewise.
	(OPENJDK_SHA256SUM): Likewise.
	* NEWS: Updated.
	* configure.ac: Bump to 2.4.8.
	* hotspot.map: Update to icedtea-2.4.8 tag.
	* patches/boot/ecj-diamond.patch: Regenerated.